robot_index:
    label: robots index
    type: balloon-selector
    tab: Robots
    options:
        index: index
        noindex: noindex
    comment: eugene3993.robots::lang.config.index
    span: left
    default: index

robot_follow :
    label   : robots follow
    type    : balloon-selector
    tab     : Robots
    options :
        follow: follow
        nofollow: nofollow
    comment : eugene3993.robots::lang.config.follow
    span    : right
    default : follow